name = "Simpl"
license = "MIT"
licenselink = "https://gitlab.com/bplatta/simpl/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["blog", "minimal", "responsive"]
features = ["responsive"]
min_version = 0.17

[author]
  name = "bplatta"
  homepage = "https://gitlab.com/bplatta/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
