baseurl = "https://mybaseurl.com/"
languageCode = "en-US"
title = "My great site"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "simpl"

[permalinks]
  blog = "/blog/:year/:month/:slug"

[params]
  avatar = "profile.png"
  author = "Ben Platta"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  Github        = "username"
  Gitlab        = "username"
  Email         = "email@email.com"
  LinkedIn      = "linkedin-public-username-id"
  Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 200
  url = "/about/"
